sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shivamkaushik91/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shivamkaushik91/docker-react npm run test
